### ISSUE TITLE
Sony RX10 IV PCMA dont work ?

### ISSUE THREAD

**Issue by camperschwein** [ma1co/OpenMemories-Framework#14] opened 2017-10-07 20:18 UTC
If i will install the Open Memories Tweak the folloing messenge is comming:

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX10M4 is a camera in MTP mode

Model:              DSC-RX10M4
Product code:       0080817550
Serial number:      -
Firmware version:   1.00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX10M4 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "<string>", line 73, in do
  File "pmca\commands\usb.py", line 211, in installCommand
  File "pmca\commands\usb.py", line 31, in switchToAppInstaller
  File "pmca\usb\sony.py", line 180, in switchToAppInstaller
  File "pmca\usb\sony.py", line 147, in _sendCommand
  File "pmca\usb\sony.py", line 94, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2006

Can someone help me ?

**Comment by ma1co** [comment] 2017-10-08 15:37
Duplicate of [this](https://github.com/ma1co/Sony-PMCA-RE/issues/46)

**Closed by ma1co** 2017-10-08 15:37 UTC
